apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: default
spec:
  containers:
  - name: redis
    image: docker.m.daocloud.io/redis:8.4
    ports:
    - containerPort: 6379
      name: redisport
    securityContext:
      runAsUser: 999
    volumeMounts:
    - mountPath: /data
      name: redisdata
  volumes:
  - name: redisdata
    persistentVolumeClaim:
      claimName: pvc-nfs-dynamic
