apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
