apiVersion: v1
kind: Pod
metadata:
  namespace: test
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: docker.m.daocloud.io/nginx:stable-alpine3.23
    name: nginx
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
