apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx-with-dnspolicy
spec:
  containers:
   - name: nginx
     image: docker.m.daocloud.io/nginx:stable-alpine3.23
     imagePullPolicy: IfNotPresent
   dnsPolicy: None
   dnsConfig:
     namespace:
     - 10.96.0.10
     - 223.5.5.5
     - 223.6.6.6
     searches:
     - svc.cluster.local
     - cluster.local
     - ilinux.io
     options:
     - name: ndots
       values: "5"
