apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: ops-mongo
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    tls:
      certificateKeySecretRef:
        name: ops-mongo-cert
      caCertificateSecretRef:
        name: ops-mongo-ca
      enabled: true
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongo-admin-pw
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: ops-mongo-scram

  # --- 核心修改区：所有资源配置必须包裹在 statefulSet.spec 之下 ---
  statefulSet:
    spec:
      # 1. 存储卷定义 (必须移到这里，否则报 unknown field)
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: openebs-hostpath
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
        - metadata:
            name: logs-volume
          spec:
            storageClassName: openebs-hostpath
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      template:
        spec:
          initContainers:
            - name: check-and-fix-permissions
              image: docker.m.daocloud.io/busybox:1.37.0
              command: ["sh", "-c", "chown -R 999:999 /data && chown -R 999:999 /var/log/mongodb-mms-automation"]
              securityContext:
                runAsUser: 0
              volumeMounts:
                - name: data-volume
                  mountPath: /data
                - name: logs-volume
                  mountPath: /var/log/mongodb-mms-automation
          securityContext:
            fsGroup: 999
            runAsUser: 999
            runAsGroup: 999
          containers:
            - name: mongod
              volumeMounts:
                - name: data-volume
                  mountPath: /data
                - name: logs-volume
                  mountPath: /var/log/mongodb-mms-automation
              resources:
                limits:
                  cpu: "500m"
                  memory: "1Gi"
                requests:
                  cpu: "200m"
                  memory: "512Mi"
