apiVersion: v1
kind: Pod
metadata:
  name: liveness-httpget-demo
  namespace: default
spec:
  containers:
  - name: demo
    image: docker.m.daocloud.io/library/nginx:stable-alpine3.23
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: '/'
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
