apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: default
spec:
  containers:
  - name: demo
    image: docker.m.daocloud.io/library/nginx:stable-alpine3.23
    imagePullPolicy: IfNotPresent
    startupProbe:
      exec:
        command: ["/bin/sh", "-c", "wget -qO- http://127.0.0.1 >/dev/null"]
      initialDelaySeconds: 5
      failureThreshold: 3
      periodSeconds: 5
