apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ops
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-headless # 必须是 Headless Service
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
      - name: init-mysql
        image: docker.m.daocloud.io/mysql:8.0
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # 这会把 "mysql-0" 注入环境变量
        command:
        - bash
        - "-c"
        - |
          set -ex
          # 改用环境变量 POD_NAME，不再调用 hostname 命令
          [[ $POD_NAME =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          if [[ $ordinal -eq 0 ]]; then
            cp /mnt/config-map/master.cnf /etc/mysql/conf.d/
          else
            cp /mnt/config-map/slave.cnf /etc/mysql/conf.d/
            sed -i "s/server-id=2/server-id=$((2 + $ordinal))/" /etc/mysql/conf.d/slave.cnf
          fi
        volumeMounts:
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: config-map
          mountPath: /mnt/config-map
      containers:
      - name: mysql
        image: docker.m.daocloud.io/mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: openebs-hostpath # 使用你的 NFS 存储
      resources:
        requests:
          storage: 10Gi
