---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 2
       maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: v3.23
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        version: v3.23
    spec:
      containers:
      - image: docker.m.daocloud.io/nginx:1.28.1-alpine3.23-perl
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-ip-version-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ip-version-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
        default_type text/plain;
        # $server_addr 是容器的私有 IP
        # $nginx_version 是 Nginx 的当前版本
        return 200 "Server IP: $server_addr  Nginx Version: $nginx_version\n";
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
