apiVersion: v1
kind: Service
metadata:
  name: svc-external
  namespace: default
spec:
  type: ExternalName
  extarnalName: yubowe.github.io
  ports:
  - protocol: tcp
    port: 80
    targetPort: 80

