apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openebs-check
  namespace: default
spec:
  serviceName: "check"
  replicas: 2
  selector:
    matchLabels:
      app: openebs-check
  template:
    metadata:
      labels:
        app: openebs-check
    spec:
      containers:
      - name: nginx
        image: docker.m.daocloud.io/nginx:stable-alpine3.23
        volumeMounts:
        - name: my-data
          mountPath: /data
        command: ["/bin/sh", "-c"]
        # 每个副本在自己的存储里写下自己的名字
        args: ["echo $(hostname) > /data/info.txt && sleep 3600"]
  volumeClaimTemplates:
  - metadata:
      name: my-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: openebs-hostpath # 确保这名字和你创建的 SC 一致
      resources:
        requests:
          storage: 1Gi
