apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demoapp
  name: demoapp
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp
  type: LoadBalancer
status:
  loadBalancer: {}

