apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: jenkins-master
  namespace: jenkins
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: jenkins
spec: {}
status: {}
