apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        # 使用特定的稳定版本，避免 latest 的不确定性
        image: docker.1ms.run/provectuslabs/kafka-ui:v0.7.2 
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "my-cluster"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "my-cluster-kafka-bootstrap:9092"
        # 增加资源限制，防止 UI 占用过多内存
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
  namespace: kafka
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kafka-ui
